apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-tjms
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-tjms
    app.kubernetes.io/part-of: my-app
  name: dc-metro-map-tjms
  namespace: karthik-jk-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dc-metro-map-tjms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: dc-metro-map-tjms
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/uidev-user-workload@sha256:11f1bc821175e4af80ab4e4be330ddf9df7df142a1c5faca0fa319f6519e6cc7
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
