apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: stonesoup
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: stonesoup
    app.kubernetes.io/part-of: my-app
  name: stonesoup
  namespace: karthik-jk-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: stonesoup
    weight: 100
status: {}
