apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-tjms
  namespace: karthik-jk-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/uidev-user-workload@sha256:9f5e546f55cb338cc6df2cdca424175242bb129d580bd13a46d80ee65b71388e
        name: container-image
        resources: {}
status: {}
